audit_header: false
title: Harrisonburg Real Estate Video Blog with Brad Cohen
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Refer a Friend
    url: /refer/
  - title: Testimonials
    url: https://www.zillow.com/profile/bradcohenrealtor/#reviews
client:
  name: Brad Cohen
  title:
  license_number:
  about_markdown: >-
    Brad Cohen balances extensive real estate market knowledge and expertise
    with personality and a fun-loving approach to provide his clients with a
    simply better buying and selling experience. His charm and wit are
    complemented by direct communication and a true desire to help people.


    Brad has been a top-producing agent since his first year. He has been a
    Virginia Realtors® Spotlighted Member, grown his business annually, and
    recorded over $15 Million in sales in 2021. To date, he has helped over 150
    buyers and sellers reach their real estate goals.


    Brad is a dog dad of 2, JMU Alum, involved community leader, skydiver and
    bourbon enthusiast.


    Brad is your go-to local expert for all things Harrisonburg, real estate,
    and beyond. Contact him anytime at 540-830-7239 or visit
    brad@bradcohenhomes.com
  market: Harrisonburg
  brand:
  brokerage:
  address: 1741 A Virginia Ave, Harrisonburg, VA 22801
  phone: 540-830-7239
  phone_type:
  phone2:
  phone2_type:
  email: brad@bradcohenhomes.com
  url: http://bradcohenrealtor.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://cohenteam.smarthomeprice.com/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.harmanrealtypropertysearch.com/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://cohenteam.smarthomeprice.com/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://www.harmanrealtypropertysearch.com/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/BradCohenRealtor/
  linkedin_url: https://www.linkedin.com/in/bradcohenrealtor/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCsQwfzIkd2najn8ONNNZdQg
  twitter_url: https://twitter.com/BCohenRealtor
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/bradcohenrealtor/
  trulia_url: >-
    https://www.trulia.com/profile/brad-cohen-agent-harrisonburg-va-zg8v6y56/overview
  yelp_url: >-
    https://www.yelp.com/biz/brad-cohen-realtor-funkhouser-harrisonburg?osq=brad+cohen+realtor
  podcast_url: >-
    https://itunes.apple.com/us/podcast/harrisonburg-real-estate-podcast-with-brad-cohen/id1403966286?mt=2
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/untitled-design-7.png
  logo_width_number: 40
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0a7abe'
  theme_color: '#383f49'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(238, 238, 238, .75)
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
